### PR TITLE
Reliable UTF-8 behaviour (closes #35)

### LINKED ISSUE #35: Add setting to disable UTF-8 encoding in Websocket::Frame
There are two problems with automatic encoding/decoding UTF-8

First of all, this doesn't make any sense on BINARY packets, so these should never handled as possible UTF-8 encoded strings (i failed with exactly this kind of error when trying to implement a proxy for noVNC).

Secondly, on TEXT type messages, UTF-8 could use either automatic mode (default) or off. This is because i might want to pass the messages through and handle encoding later.

### PR DESCRIPTION
**Pull request by leonerd**
Always UTF-8 encode the buffer of text frames; never encode others

### CODE REVIEW

**Comment by vti** [comment]
I think that is_utf8 makes sense for text anyway. People tend to forget to decode their strings. What worries me is that this change will be backwards incompatible and can break some code.

**Comment by leonerd** [comment]
`is_utf8` never makes sense from pureperl code. The only thing it tells you is the internal format of the `SvPVX` buffer inside the `SVt_PV` containing that string. You can't actually make use of that information in any way from pureperl code.

In particular it does *not* reliably tell you whether the string contains "Unicode" characters or not.

Given a string with codepoints > 0xff, e.g.

    "UTF\x{2010}8"

then this flag is *necessarily* true, because a single byte cannot contain the U+2010 character.

However, a string such as

    "caf\x{00e9}"

may or maynot have the utf8 flag set on it. It is possible to store that string in four bytes ("\x63\x61\x66\xe9" with utf8 off), or in five ("\x63\x61\x66\xc3\xa9" with utf8 on). Either is valid and either could appear in a program as a result of the operations that created it.

Correctly-written perl code will always treat the two as the same; this use of `Encode::is_utf8` by Frame.pm will not.

**Comment by leonerd** [comment]
Expressed a different way perhaps: If you only ever test this with US-ASCII text (i.e. no "Unicode") then the value that the `Encode::is_utf8` flag has does not matter, as either true or false the same bytes will occur with or without UTF-8 encoding and all is happy.

If you only ever test with US-ASCII plus characters outside of Latin-1 (e.g. Russian, Greek, CJK, anything else), then that flag will always be true, and you'll always correctly be UTF-8 encoding and get the correct bytes.

The failure case here is when the string contains non-ASCII Latin-1 characters - Unicode codepoints in the range `[\xa0-\xff]`. Characters in that range may or maynot be stored internally in perl strings using its "utf8" encoding, and thus may or maynot end up passing through `Encode::encode('UTF-8')` here, and thus may or maynot be emitted correctly on the websocket wire.

**Comment by vti** [comment]
I understand that `is_utf8` doesn't tell me if the string is Unicode or not. But what it tells me is that when somebody slurps unicode file in a string and forgets to use `:encoding(utf-8)` or `Encode::decode($content)` and then sends that data with `Protocol::WebSocket` frame it will not croak. Also it will skip decoding/encoding when it's not needed.

**Comment by leonerd** [comment]
> But what it tells me is that when somebody slurps unicode file in a string and forgets to use :encoding(utf-8) or Encode::decode($content)

But see my later comment. It doesn't *reliably* tell you this. It only reliably tells you that for non-Latin1 Unicode - codepoints `U+0100` and above - Russian, Greek, CJK, anything else. It doesn't reliably flag up the intent to store Unicode characters between U+00A0 and U+00FF, because perl may **arbitrarily at its own discretion** decide to store those internally using the "utf8"-like encoding or not.

**Comment by vti** [comment]
Hm, I didn't know about this A0-FF issue. Thanks for clarifying.

**Pull request merged**
